random_state: 42

model:
  shuffle: True
  batch_size: 1024
  epochs: 70
  learning_rate: 0.002
  optimizer: Adam
  activation_function: relu
  loss_function: MSELoss
  fc_layers:
    - type: Linear
      in_features: 1
      out_features: 32
    - type: Dropout
      p: 0.3
    - type: Linear
      in_features: 32
      out_features: 128
    - type: Dropout
      p: 0.3
    - type: Linear
      in_features: 128
      out_features: 1024
    - type: Dropout
      p: 0.3
    - type: Linear
      in_features: 1024
      out_features: 6272
  view_shape:
    channels: 128
    height: 7
    width: 7
  deconv_layers:
    - type: ConvTranspose2d
      in_channels: 128
      out_channels: 32
      kernel_size: 4
      stride: 2
      padding: 1
    # - type: BatchNorm2d
    #   num_features: 32
    - type: Dropout2d
      p: 0
    - type: ConvTranspose2d
      in_channels: 32
      out_channels: 1
      kernel_size: 4
      stride: 2
      padding: 1

evaluation:
  train: True
  test: True
  epoch_frequency: 1
  shuffle: True

cross_validation:
  tune: True
  k_folds: 5
  shuffle: True
  metric_to_optimize: average_mse
  param_grid:
    shuffle: [True]
    batch_size: [1024]
    epochs: [70]
    learning_rate: [0.002]
    optimizer: [Adam]
    activation_function: [relu]
    dropout: [0.3]
    dropout2d: [0, 0.1, 0.2, 0.3, 0.4, 0.5]

logging:
  log_to_wandb: True
  project_name: 'mnist_cnn_image_generator'
