random_state: 42

model:
  shuffle: True
  batch_size: 2048
  epochs: 50
  learning_rate: 0.002
  optimizer: Adam
  activation_function: relu
  loss_function: MSELoss
  fc_layers:
    - type: Linear
      in_features: 1
      out_features: 64
    - type: Dropout
      p: 0.2
    - type: Linear
      in_features: 64
      out_features: 128
    - type: Dropout
      p: 0.2
    - type: Linear
      in_features: 128
      out_features: 3136
  view_shape:
    channels: 64
    height: 7
    width: 7
  deconv_layers:
    - type: ConvTranspose2d
      in_channels: 64
      out_channels: 32
      kernel_size: 4
      stride: 2
      padding: 1
    - type: BatchNorm2d
      num_features: 32
    - type: Dropout2d
      p: 0.2
    - type: ConvTranspose2d
      in_channels: 32
      out_channels: 1
      kernel_size: 4
      stride: 2
      padding: 1

evaluation:
  train: True
  test: True
  epoch_frequency: 1
  shuffle: True

cross_validation:
  tune: False
  k_folds: 5
  shuffle: True
  metric_to_optimize: average_accuracy
  param_grid:
    shuffle: [True]
    batch_size: [512]
    epochs: [20]
    learning_rate: [0.001]
    optimizer: [Adam]
    activation_function: [relu]
    dropout: [0.20]

logging:
  log_to_wandb: False
  project_name: 'mnist_cnn'
