random_state: 42

model:
  shuffle: True
  batch_size: 128
  epochs: 20
  learning_rate: 0.002
  optimizer: Adam
  activation_function: tanh
  loss_function: MSELoss
  fc_layers:
    - in_features: 1
      out_features: 128
    - in_features: 128
      out_features: 256
    - in_features: 256
      out_features: 512
    - in_features: 512
      out_features: 1024
    - in_features: 1024
      out_features: 6272
  view_shape:
    channels: 128
    height: 7
    width: 7
  deconv_layers:
    - in_channels: 128
      out_channels: 64
      kernel_size: 4
      stride: 2
      padding: 1
    - in_channels: 64
      out_channels: 1
      kernel_size: 4
      stride: 2
      padding: 1

evaluation:
  train: True
  test: True
  epoch_frequency: 1
  shuffle: True

cross_validation:
  tune: False
  k_folds: 5
  shuffle: True
  metric_to_optimize: average_accuracy
  param_grid:
    shuffle: [True]
    batch_size: [2048]
    epochs: [40]
    learning_rate: [0.001]
    optimizer: [Adam]
    activation_function: [tanh]
    dropout: [0.20]

logging:
  log_to_wandb: False
  project_name: 'mnist_cnn'
